name: cdrc_env

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - seaborn
  - matplotlib==3.*
  - geopandas
  - mapclassify
  - cartopy
  - descartes
  - ipywidgets
  - pyproj
  - jupyterlab>=1.0
  - jupyter==1.0.0
  - contextily
  - pip:
      - plotly
      - statsmodels
      - scikit-learn
     
